import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Left_Navigation_Main from "@/app/Componants/Left_Navigation/Left_Navigation_Main";
import Navbar_Main from "@/app/Componants/Navbar/Navbar_Main";
import SettingMain from "@/app/Componants/Setting/SettingMain";
import ContextProvider from "@/app/ContextProvider"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dua & Ruqyah",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-[#ebeef2] antialiased`}
        >
        <ContextProvider>
        <div className="flex p-0 xl:p-10 h-screen overflow-hidden text-center  ">
          <Left_Navigation_Main />
          <div className=" w-screen ">
            <header className=" ">
              <Navbar_Main />
            </header>

            <div className="flex justify-between   h-full  ">
            

              {children}
             

              <SettingMain />
            </div>
          </div>
        </div>

        </ContextProvider>
      </body>
    </html>
  );
}
